### ISSUE TITLE
The `n` choice when selecting repository in `git machete github create-pr` doesn't make sense

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#216]
```
➜ 16:36 ~/git-machete chore/refer-to-docs $ git machete github create-pr 
Push untracked branch chore/refer-to-docs to origin? (y, q, o[ther-remote]) o
[1] asford
[2] origin
Select number 1..2 to specify the destination remote repository, or 'n' to skip this branch, or 'q' to quit the traverse: n

  master  v3.3.0
  │ 
  └─develop  v3.4.0
    │ 
    └─enchance/checkout-pr  v3.4.0
    │ 
    └─chore/refer-to-docs (untracked)  v3.4.0

Creating a PR from chore/refer-to-docs to develop...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/github.py", line 123, in __fire_github_api_request
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/git-machete", line 4, in <module>
    __import__('pkg_resources').run_script('git-machete==3.4.0', 'git-machete')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/EGG-INFO/scripts/git-machete", line 4, in <module>
    __import__('pkg_resources').run_script('git-machete==3.4.0', 'git-machete')
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/cmd.py", line 1816, in main
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/cmd.py", line 2079, in launch
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/cmd.py", line 1592, in create_github_pr
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/github.py", line 166, in create_pull_request
  File "/usr/local/lib/python3.7/site-packages/git_machete-3.4.0-py3.7.egg/git_machete/github.py", line 128, in __fire_github_api_request
git_machete.exceptions.UnprocessableEntityHTTPError: Unprocessable Entity
Please open an issue regarding this topic under link: https://github.com/VirtusLab/git-machete/issues/new
➜ (1) 16:37 ~/git-machete chore/refer-to-docs $ git machete github create-pr --debug
```

**Comment by rifel123** [comment]
closed with #240
